### PR TITLE
Allow an .env file to be used instead of credentials, catch KeyringEr…

### PR DESCRIPTION
**Pull request by evanjt**
Allows a user to set the credentials with an .env file.

Furthermore, adding exception handling should the keyring library throw an error in the case the keyring is not found, or locked, etc.

### CODE REVIEW

**Comment by evanjt** [comment]
```
$ earth-extractor credentials --show-secrets
                                                                  
│ Credential key          │ Value                                                                                                                                                                                                           
│ SCIHUB_USERNAME         │ ejayt                                                                                                                                                                                                           │
│ SCIHUB_PASSWORD         │ fakepass                                                                                                                                                                                                    │
│ NASA_TOKEN              │ faketoken 
│ SINERGISE_CLIENT_ID     │ test                                                                                                                                                                                                            │
│ SINERGISE_CLIENT_SECRET │ test                                                                                                                                                                                                            │                                                                                                                                                                                                      
```

Create `.env` file with other values:
```
cat <<EOF > .env
SCIHUB_USERNAME=1234
SCIHUB_PASSWORD=5678
NASA_TOKEN=abcdefg
SINERGISE_CLIENT_ID=tttttt
SINERGISE_CLIENT_SECRET=hhhhhh
EOF
```

```
$ earth-extractor credentials --show-secrets
│ SCIHUB_USERNAME         │ 1234    │
│ SCIHUB_PASSWORD         │ 5678    │
│ NASA_TOKEN              │ abcdefg │
│ SINERGISE_CLIENT_ID     │ tttttt  │
│ SINERGISE_CLIENT_SECRET │ hhhhhh  │
```

**Review by ymarcon — APPROVED** [review]

**Comment by system123** [comment]
I'd prefer if the credentials were loaded directly from `os.environ`, as this is now a library it means it might be executed from many environments and having to copy an `.env` file around is more error prone than just setting the variables directly. If the user wants to use a `.env` file they can still make it and most modern terminals will autoload `.env` files from the directory you are in anyway

**Comment by evanjt** [comment]
> I'd prefer if the credentials were loaded directly from `os.environ`, as this is now a library it means it might be executed from many environments and having to copy an `.env` file around is more error prone than just setting the variables directly. If the user wants to use a `.env` file they can still make it and most modern terminals will autoload `.env` files from the directory you are in anyway

@system123 
The changes allow for that to also happen. `pydantic.BaseModel` seeks first the system environment vars, and then will look in the local `.env` file with the changes under `class Config:`.

You can try this with:
`NASA_TOKEN=token_from_environment poetry run earth-extractor credentials --show-secrets`

```
│ SCIHUB_USERNAME         │ 1234                   │
│ SCIHUB_PASSWORD         │ 5678                   │
│ NASA_TOKEN              │ token_from_environment │
│ SINERGISE_CLIENT_ID     │ tttttt                 │
│ SINERGISE_CLIENT_SECRET │ hhhhhh                 │

```

**Comment by evanjt** [comment]
I have removed reference to Sinergise to avoid ambiguity. It was a provider prototyped in the initial design and has not been used for quite some time.

**Pull request merged**
